거리 계산(매장 목록, 디테일, 좋아요 리스트)
9oj0e/pathorder_server pull request #83
Opened 2024-05-18 10:43 UTC by Hyeonjeong-JANG

# ✔️ 손님-가게 거리 계산

## 🐯 DistanceUtil
거리 계산하는 유틸이 필요함.
두 지점의 위도와 경도를 입력받아, 구면 삼각법(Haversine 공식)을 적용하여 두 지점 사이의 거리를 계산하고, 그 거리를 미터 단위로 반환함.
```
private static final double EARTH_RADIUS_KM = 6371.0;

    public static int calculateDistance(double lat1, double lon1, double lat2, double lon2) {
        double dLat = Math.toRadians(lat2 - lat1);
        double dLon = Math.toRadians(lon2 - lon1);

        double a = Math.sin(dLat / 2) * Math.sin(dLat / 2)
                   + Math.cos(Math.toRadians(lat1)) * Math.cos(Math.toRadians(lat2))
                     * Math.sin(dLon / 2) * Math.sin(dLon / 2);

        double c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
        double distanceInKm = EARTH_RADIUS_KM * c;
        double distanceInMeters = distanceInKm * 1000;
        return (int) Math.round(distanceInMeters); // 미터로 변환 후 반올림
    }
```
## 🐯 StoreResponse.StoreInfoDTO 
거리에 m를 포함시켜 String으로 반환
```
@Data // 매장 상세보기
    public static class StoreInfoDTO {
...생략
        private String distance;

        @Builder
        public StoreInfoDTO(...생략 , String distance) {
...생략
            this.distance = distance;
        }

        public StoreInfoDTO(Store store, int likeCount, boolean isLiked, int reviewCount, int distance) {
...생략
            this.distance = distance + "m";
        }
    }
```

## 🐯 StoreService.getStoreInfo()

```
public StoreResponse.StoreInfoDTO getStoreInfo(int userId, int storeId, double customerLatitude, double customerLongitude) {
        Store store = storeRepository.findById(storeId)
                .orElseThrow(() -> new Exception404("찾을 수 없는 매장입니다."));

       ...생
        int distance = DistanceUtil.calculateDistance(customerLatitude, customerLongitude, store.getLatitude(), store.getLongitude());

        return new StoreResponse.StoreInfoDTO(store, likeCount, isLiked, reviewCount, distance);
    }
```

2024-05-18 16:31 UTC, 9oj0e requested changes

2024-05-18 16:31 UTC, 9oj0e commented on src/main/java/shop/project/pathorderserver/like/LikeResponse.java
> +        private String distance;
DistanceUtil이 int를 출력하는데
혹시
String으로 받은 이유가
혹시 뒤에 단위를 붙이기 위해서인가요

2024-05-18 16:31 UTC, 9oj0e commented on src/main/java/shop/project/pathorderserver/user/SessionUser.java
> +        this.longitude = 129.0604337191542;
이거
sessionUser에서 위치를 받으려고 하신거같은데
제 생각에는 이렇게 하면 안될거같아요

2024-05-18 16:31 UTC, 9oj0e commented on src/main/java/shop/project/pathorderserver/store/StoreController.java
> +        List<StoreResponse.StoreListDTO> respDTO = storeService.getStoreList(sessionUser.getId(), sessionUser.getLatitude(), sessionUser.getLongitude());
만약 sessionUser에서 꺼내야하는 값이 많다면
그냥 service로 넘겨버리는게 나을 것 같기도 함

2024-05-18 16:44 UTC, Hyeonjeong-JANG commented on src/main/java/shop/project/pathorderserver/user/UserRequest.java
> +    public static class LocationReqDTO {
처음에 플러터쪽에서 경도 위도를 요청했는데 세션유저에 픽스하자해서 그걸 지움
쿼리스트링으로 경도위도주면 보안상 좋지않아서 포스트매핑으로 변경했다가 찬혁씨에게 의견을 물어봄

2024-05-18 16:46 UTC, Hyeonjeong-JANG commented on src/main/java/shop/project/pathorderserver/like/LikeResponse.java
> +        private String distance;
처음에 그냥 인트로 했다가 m붙이기 위해 스트링으로 바꿨는데 터팀에 물어보니 상관없다해서 그냥 놔둠
수정가능

2024-05-18 16:47 UTC, Hyeonjeong-JANG commented on src/main/java/shop/project/pathorderserver/user/SessionUser.java
> +        this.longitude = 129.0604337191542;
난 포스트매핑으로 위도경도를 받는 것이 좋다고 생각했음.
그러나 터팀의 요구사항이 세션에 담아서 해달라는 것이었음.
수정가능

2024-05-19 04:49 UTC, 9oj0e commented on src/main/java/shop/project/pathorderserver/user/SessionUser.java
> +        this.longitude = 129.0604337191542;
<img width="800" alt="스크린샷 2024-05-19 오후 1 49 32" src="https://github.com/9oj0e/pathorder_server/assets/126438339/877b39a5-66cf-4358-b372-a70861eba6d7">

2024-05-19 06:10 UTC, 9oj0e approved these changes

2024-05-19 06:10 UTC, 9oj0e commented on src/main/java/shop/project/pathorderserver/user/SessionUser.java
> +        this.longitude = 129.0604337191542;
시간제약이 있으니, 거리 계산은 SSR로 하는걸로 good

2024-05-19 06:10 UTC, merged